// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// camax_u
int camax_u(arma::vec& x);
RcppExport SEXP _anRpackage_camax_u(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec& >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(camax_u(x));
    return rcpp_result_gen;
END_RCPP
}

RcppExport SEXP _anRpackage_rcpparma_bothproducts(SEXP);
RcppExport SEXP _anRpackage_rcpparma_hello_world();
RcppExport SEXP _anRpackage_rcpparma_innerproduct(SEXP);
RcppExport SEXP _anRpackage_rcpparma_outerproduct(SEXP);

static const R_CallMethodDef CallEntries[] = {
    {"_anRpackage_camax_u", (DL_FUNC) &_anRpackage_camax_u, 1},
    {"_anRpackage_rcpparma_bothproducts", (DL_FUNC) &_anRpackage_rcpparma_bothproducts, 1},
    {"_anRpackage_rcpparma_hello_world",  (DL_FUNC) &_anRpackage_rcpparma_hello_world,  0},
    {"_anRpackage_rcpparma_innerproduct", (DL_FUNC) &_anRpackage_rcpparma_innerproduct, 1},
    {"_anRpackage_rcpparma_outerproduct", (DL_FUNC) &_anRpackage_rcpparma_outerproduct, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_anRpackage(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
